version: '4.2'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp:
